name: E2E

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: '*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # https://docs.cypress.io/guides/continuous-integration/github-actions
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Cypress run
      - uses: cypress-io/github-action@v5
        with:
          build: yarn install
          start: yarn test:e2e:ci
          browser: chrome
